{ pkgs, self, system, ... }:
{
  # Auto upgrade nix package and the daemon service.
  # services.nix-daemon.enable = true;

  # Set Git commit hash for darwin-version.
  system.configurationRevision = self.rev or self.dirtyRev or null;

  # TODO: there are settings in old /etc/nix/nix.conf generated by
  # the detsys nix installer which i haven't migrated here yet
  nix.settings.experimental-features = ''
    nix-command flakes
  '';

  fonts.packages = [ pkgs.hack-font ];

  # The platform the configuration will be used on.
  nixpkgs.hostPlatform = system;

  nixpkgs.overlays = [
    (final: prev: {
      go = prev.go.overrideAttrs (old: rec {
        version = "1.26.0";
        src = pkgs.fetchurl {
          url = "https://go.dev/dl/go${version}.src.tar.gz";
          hash = "sha256-yRMqih9r0qpKrR10uCMdlSdJUEg6SVBlfubFbm6Bd5A=";
        };
      });

      # https://github.com/NixOS/nixpkgs/issues/154163#issuecomment-1350599022
      makeModulesClosure = x: prev.makeModulesClosure (x // { allowMissing = true; });
    })
  ];
}
