live_config_reload = true

[bell]
animation = "EaseOutExpo"
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[colors.cursor]
text = "0x1d2021"
cursor = "0xd5c4a1"

[colors.normal]
black = "0x1d2021"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xd5c4a1"

[colors.bright]
black = "0x665c54"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xfbf1c7"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[env]
TERM = "alacritty-direct"

[font]
size = 12.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "L"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 0

[shell]
args = ["--login"]
program = "/Users/ehdens/.nix-profile/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2
