scan_timeout = 5
add_newline = false
format = """
$cmd_duration\
$time\
$username$hostname\
$nix_shell\
$git_branch\
$git_state\
$git_status\
$directory\
$jobs\
$character\
"""

[directory]
style = "bold blue"
fish_style_pwd_dir_length = 1

[cmd_duration]
style = "dimmed white"
show_milliseconds = true
format = "[\\($duration\\)]($style)\n"

[username]
style_user = "bold dimmed blue"
format = "[$user]($style)"

[hostname]
style = "bold dimmed blue"
format = "[@$hostname]($style) "

[time]
disabled = true
format = "[$time]($style) "
style = "bold green"

[git_branch]
style = "purple"
format = "[$symbol$branch]($style) "

[battery]
disabled = true

[git_status]
# re-enabling for now to see how it behaves with potential performance improvements
# disabled = true

[nix_shell]
# this appears to add an extra space following "character" when enabled if
# state is a snowflake, and not otherwise. starship (or alacritty? or tmux?)
# may have trouble counting non-single width characters in the prompt
#
# in fucking around w/ this elsehwere, it may be tmux's fault
format = '[$state \($name\)]($style) '
# impure_msg = "❄️"
# impure_msg = "🤗"
impure_msg = "n"
pure_msg = "[n](green)"

[aws]
symbol = ""
