vim.g.mapleader = ','

-- don't try to load perl provider
-- (other providers are disabled for me in code generated by nix)
vim.g.loaded_perl_provider = 0

-- remap split switching
vim.keymap.set('n', '<tab>', '<c-w>')

-- change j and k to move by row instead of by line
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', 'k', 'gk')

-- relative line numbers
vim.opt.number = true
vim.opt.relativenumber = true

-- some minor performance things
vim.opt.showcmd = false
vim.opt.lazyredraw = true

-- default tab behavior
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4

-- search settings
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.hlsearch = false

-- path separator is not OS 
vim.opt.undodir = vim.fn.stdpath('cache') .. '/vimdid'
vim.opt.undofile = true

-- yank to clipboard
vim.opt.clipboard = 'unnamed'
-- copy clipboard in between "" or '
vim.keymap.set('n', '<leader>"', 'i"<Esc>p', { silent = true })
vim.keymap.set('n', '<leader>\'', 'i\'<Esc>p', { silent = true })

-- https://github.com/neovim/neovim/issues/416 changed the default for Y to y$,
-- which is admittedly more sensible, but my fingers refuse. double tapping y
-- feels worse/slower than shift-y just because of where y is
vim.keymap.set('n', 'Y', 'yy')

-- remap next/previous buffer
vim.keymap.set('n', '<C-n>', ':bnext<CR>', { silent = true })
vim.keymap.set('n', '<C-m>', ':bprev<CR>', { silent = true })
vim.keymap.set('n', '<C-e>', ':e#<CR>', { silent = true })

-- fold with treesitter
vim.opt.foldlevelstart = 99 -- so files are not folded when vim starts
vim.opt.foldmethod = 'expr'
vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'

-- move selected text up/down with J/K
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
